# Generated by Django 5.2.13 on 2026-04-29 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KunTartibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Nomi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('rang', models.CharField(default='#4CAF50', max_length=7, verbose_name='Rang (hex)')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kun_tartiblari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kun tartibi',
                'verbose_name_plural': 'Kun tartiblari',
                'db_table': 'kun_tartibi',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='KunTartibiKunligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('bajarildi', models.BooleanField(default=True, verbose_name='Bajarildi')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('kun_tartibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunliklar', to='habits.kuntartibi')),
            ],
            options={
                'verbose_name': 'Kunlik qayd',
                'verbose_name_plural': 'Kunlik qaydlar',
                'db_table': 'kun_tartibi_kunligi',
                'ordering': ['-sana'],
                'unique_together': {('kun_tartibi', 'sana')},
            },
        ),
    ]
